---
title: "Modelos Jerarquicos en Ecologia"
subtitle    : "Entendiendo la foto mas grande"
author      : Diego J. Lizcano, ULEAM
job         : "ULEAM"
logo        : img/TSG.png
biglogo     : img/tsg_logo.gif

date        : June 15, 2016 @ WCS, Quito

output      : ioslides_presentation
---


## Árbol de decisión de modelos en el paquete unmarked

```{r diagram,echo=FALSE}
library(DiagrammeR)

grViz("
digraph DAG {

  # Intialization of graph attributes
  graph [overlap = true]

  # Initialization of node attributes
  node [shape = box,
        fontname = Helvetica,
        color = blue,
        type = box
        ]

  # Initialization of edge attributes
  edge [color = green,
        rel = yields]

  # Node statements
  occu; conteo; ocupacion; pcount; muestreo; pcountOpen; colext


  # Edge statements
   ocupacion->occu; ocupacion->colext; muestreo->conteo; muestreo->ocupacion; conteo->pcountOpen; conteo->pcount
}
")
```


## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

